name: emergency_service_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2+1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2
  google_fonts: ^8.1.0  # এটি বাদ পড়েছিল
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0